document.writeln(" <div class=\'lj\'>");
document.writeln(" 	<div class=\'container\'  style=\'padding-bottom:3%;border-bottom:1px solid  rgba(255,255,255,.1)\'>");
document.writeln("    	<ul>");
document.writeln("        	<li data-effect=\'slide-bottom\'>");
document.writeln("            	<h4>产品服务</h4>");
document.writeln("                <a href=\'#\'>集运头等舱</a>");
document.writeln("                <a href=\'#\'>拼箱头等舱</a>");
document.writeln("                <a href=\'#\'>空运头等舱</a>");
document.writeln("                <a href=\'#\'>拖车</a>");
document.writeln("                <a href=\'#\'>滴滴询价</a>");
document.writeln("                <a href=\'#\'>跨境电商物流</a>");
document.writeln("            </li>");
document.writeln("            <li data-effect=\'slide-bottom\'>");
document.writeln("            	<h4>查询工具</h4>");
document.writeln("                <a href=\'#\'>箱货跟踪</a>");
document.writeln("                <a href=\'#\'>船期查询</a>");
document.writeln("                <a href=\'#\'>船计划查询</a>");
document.writeln("                <a href=\'#\'>船舶定位</a>");
document.writeln("                <a href=\'#\'>拖车定位</a>");
document.writeln("                <a href=\'#\'>HS Code查询</a>");
document.writeln("                <a href=\'#\'>拖车费用查询</a>");
document.writeln("                <a href=\'#\'>内装费用查询</a>");
document.writeln("                <a href=\'#\'>报关费用查询</a>");
document.writeln("                <a href=\'#\'>海运保险费用查询</a>");
document.writeln("            </li>");
document.writeln("            <li data-effect=\'slide-bottom\'>");
document.writeln("            	<h4>物流新闻</h4>");
document.writeln("                <a href=\'#\'>海运咨询</a>");
document.writeln("                <a href=\'#\'>空运咨询</a>");
document.writeln("                <a href=\'#\'>航贸百科</a>");
document.writeln("                <a href=\'#\'>全球贸易</a>");
document.writeln("                <a href=\'#\'>供应链</a>");
document.writeln("                ");
document.writeln("            </li>");
document.writeln("            <li data-effect=\'slide-bottom\'>");
document.writeln("            	<h4>关于我们</h4>");
document.writeln("                <a href=\'#\'>人才招聘</a>");
document.writeln("                <a href=\'#\'>公司新闻</a>");
document.writeln("                <a href=\'#\'>服务条款</a>");
document.writeln("                <a href=\'#\'>联系我们</a>");
document.writeln("                ");
document.writeln("            </li>");
document.writeln("            <li data-effect=\'slide-bottom\'>");
document.writeln("            	<h4>常见问题</h4>");
document.writeln("                <a href=\'#\'>注册和密码</a>");
document.writeln("                <a href=\'#\'>我是货主</a>");
document.writeln("                <a href=\'#\'>我是物流商</a>");
document.writeln("                <a href=\'#\'>在线拖报下单</a>");
document.writeln("                <a href=\'#\'>发布货盘</a>");
document.writeln("                <a href=\'#\'>订舱条款</a>");
document.writeln("                <a href=\'#\'>拖车附加费</a>");
document.writeln("                <a href=\'#\'>拖车调度方案</a>");
document.writeln("            </li>");
document.writeln("            <li data-effect=\'slide-bottom\'>");
document.writeln("            	<h4>产品服务</h4>");
document.writeln("                <a href=\'#\'>集运头等舱</a>");
document.writeln("                <a href=\'#\'>拼箱头等舱</a>");
document.writeln("                <a href=\'#\'>空运头等舱</a>");
document.writeln("                <a href=\'#\'>拖车</a>");
document.writeln("                <a href=\'#\'>滴滴询价</a>");
document.writeln("                <a href=\'#\'>跨境电商物流</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln(" </div>");
document.writeln(" ");
document.writeln("");
document.writeln("  <div id=\'copyrights\' >");
document.writeln("    <div class=\'container\'>");
document.writeln("      <p style=\'font-size:12px;line-height:24px;\'>");
document.writeln("        © Copyright 2012-2020 运去哪 沪ICP备12035978号-2 版权所有查看营业执照<br>上海汇航捷讯网络科技有限公司地址：上海市浦东新区灵山路958号9号楼 ");
document.writeln("      </p>");
document.writeln("     ");
document.writeln("    </div>");
document.writeln("  </div> ");