document.writeln("  <div id=\'topnav\' class=\'navbar navbar-inverse\' role=\'navigation\' style=\'z-index:999\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'navbar-header\'>");
document.writeln("        <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("            <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("          </button>");
document.writeln("        <a class=\'navbar-brand\' href=\'index.html\' class=\'smoothscroll\' style=\'margin-top:2%\'><img src=\'img/logo.png\' width=\'120\'></a>");
document.writeln("      </div>");
document.writeln("      <div class=\'collapse navbar-collapse\'>");
document.writeln("        <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("          <li class=\'active\'><a href=\'index.html\' class=\'smoothscroll\'>首页</a></li>");
document.writeln("          <li>");
document.writeln("          	<a  class=\'smoothscroll\'>产品服务</a>");
document.writeln("            <ul class=\'inner-dropdown\'>");
document.writeln("						<li><a href=\'cp1.html\'>集运头等舱</a></li>");
document.writeln("						<li><a href=\'cp2.html\'>拼箱头等舱</a></li>");
document.writeln("						<li><a href=\'cp3.html\'>空运头等舱</a></li>");
document.writeln("                        <li><a href=\'cp4.html\'>拖车</a></li>");
document.writeln("						<li><a href=\'cp5.html\'>滴滴询价</a></li>");
document.writeln("						<li><a href=\'cp6.html\'>跨境物流电商</a></li>");
document.writeln("					</ul>");
document.writeln("         </li>");
document.writeln("          <li>");
document.writeln("          	<a href=\'#features\' class=\'smoothscroll\'>查询工具</a>");
document.writeln("            <ul class=\'inner-dropdown\'>");
document.writeln("						<li><a href=\'cx1.html\'>箱货查询<span style=\'color:#ff6726;margin-left:2%;font-size:12px;\'>可查抵港</span></a></li>");
document.writeln("						<li><a href=\'cx2.html\'>船期查询</a></li>");
document.writeln("						<li><a href=\'cx3.html\'>拖车定位</a></li>");
document.writeln("                        <li><a href=\'cx4.html\'>船计划查询</a></li>");
document.writeln("						<li><a href=\'cx5.html\'>HS Code查询</a></li>");
document.writeln("						<li><a href=\'cx6.html\'>船舶定位</a></li>");
document.writeln("                        <li><a href=\'cx7.html\'>拖车费用查询</a></li>");
document.writeln("                        <li><a href=\'cx8.html\'>内装费用查询</a></li>");
document.writeln("                        <li><a href=\'cx9.html\'>报关费用查询</a></li>");
document.writeln("                        <li><a href=\'cx10.html\'>海运保险费用查询</a></li>");
document.writeln("					</ul>");
document.writeln("         </li>");
document.writeln("          <li><a href=\'zq.html\'>中远海运专区</a></li>");
document.writeln("           <li><a href=\'new.html\'>物流新闻</a></li>");
document.writeln("            <li><a href=\'about.html\'>关于我们</a></li>");
document.writeln("             <li><a href=\'wl.html\'>物流管家</a></li>");
document.writeln("             ");
document.writeln("           <li class=\'dl\'>  <a href=\'../login.html\' style=\'background:#0A81D7;color:#fff;font-size:16px;margin:12px 0;padding:2px 15px;font-weight:bold;margin-left:30px\'>登录</a></li>");
document.writeln("           <li class=\'zc\'><a href=\'../regist.html\' style=\'background:none;color:#0A81D7;font-size:16px;margin:12px 0;padding:2px 15px;font-weight:bold\'>注册</a></li>");
document.writeln("        </ul>");
document.writeln("        ");
document.writeln("        ");
document.writeln("      </div>");
document.writeln("      <!--/.nav-collapse -->");
document.writeln("    </div>");
document.writeln("  </div>");