document.writeln("    	<div class=\'cp1_lf\' data-effect=\'slide-left\' style=\'padding:0 0 33px 0;overflow:visible;box-shadow:none;border-radius:6px;margin-right:2%\'>");
document.writeln("			<div class=\'leftTOP\'>");
document.writeln("			   <h6></h6>");
document.writeln("               <h4>爱上老鼠的猫</h4>           ");
document.writeln("            </div>");
document.writeln("     		<div class=\'pocket\' style=\'overflow:hidden\'>");
document.writeln("            	<div class=\'aside-lf-content\'>");
document.writeln("					<h3>运单专区<a class=\'click_icon\' href=\'javascript:;\'></a></h3>");
document.writeln("                	<ul class=\'content\' style=\'display:block\'>");
// document.writeln("                	<li class=\'tit\'><a href=\'order.html\'><b class=\'fontCol\'>*</b>创建订单</a></li>");
document.writeln("                	<li><a href=\'manageFLC.html\'>订单管理</a></li>");
document.writeln("                    <li><a href=\'Waybill_received.html\'>我收到的运单</a></li>");
document.writeln("                	<li><a href=\'problem.html\'>问题订单</a></li>");
document.writeln("                    <li><a href=\'orderSearch.html\'>订单查询</a></li>");
document.writeln("                    <li><a href=\'Logistics_information.html\'>我的物流</a></li></a>");
document.writeln("                    <li><a href=\'refund.html\'>发起退款</a></li>");
document.writeln("                	</ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'aside-lf-content\'>");
document.writeln("					<h3 class=\'iconb\'>账款中心<a href=\'javascript:;\'></a></h3>");
document.writeln("                	<ul class=\'content\' style=\'display:block\'>");
document.writeln("                	<li class=\'tit\'><a href=\'bill.html\'>我的对账单</a></li>");
document.writeln("                    <li><a href=\'My_invoice.html\'>我的发票</a></li></a>");
document.writeln("                    <li><a href=\'control_invoices.html\'>发票管理</a></li>");
document.writeln("                    <li><a href=\'monthly_closing.html\'>申请月结</a></li>");
document.writeln("                	<li><a href=\'Monthly_quota.html\'>我的月结额度</a></li>");
document.writeln("                	</ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'aside-lf-content\'>");
document.writeln("					<h3 class=\'iconb1\'>代理商<a href=\'javascript:;\'></a></h3>");
document.writeln("                	<ul class=\'content\' style=\'display:block\'>");
document.writeln("                	<li class=\'tit\'><a href=\'Apply_agent_check.html\'>申请入驻代理商</a></li>");
document.writeln("                    <li><a href=\'Apply_for_agent.html\'><b class=\'fontCol\'>*</b>申请等待</a></li>");
document.writeln("                    <li><a href=\'Apply_agent_finish.html\'><b class=\'fontCol\'>*</b>申请成功</a></li>");
document.writeln("                	</ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'aside-lf-content\'>");
document.writeln("					<h3  class=\'iconb2\'>买家中心<a class=\'click_icon\' href=\'javascript:;\'></a></h3>");
document.writeln("                	<ul class=\'content\' style=\'display:block\'>");
document.writeln("                	<li class=\'tit\'><a href=\'coupon.html\'>我的优惠卷</a></li>");
document.writeln("                    <li><a href=\'../center/ID.html\'><b class=\'fontCol\'>*</b>完善资料</a></li></a>");
document.writeln("                    <li><a href=\'information.html\'>站内信息</a></li></a>");
document.writeln("                    <li><a href=\'address.html\'>地址管理</a></li></a>");
document.writeln("                    <li><a href=\'../center/ID.html\'>身份认证</a></li></a>");
document.writeln("                    <li><a href=\'ChangePassword.html\'>修改登录密码</a></li></a>");
document.writeln("                    <li><a href=\'complain.html\'>留言投诉</a></li></a>");
document.writeln("                    <li><a href=\'complaints_manage.html\'>投诉处理</a></li></a>");
document.writeln("                    <li><a href=\'personal.html\'>个人资料</a></li></a>");
document.writeln("                    <li><a href=\'Enter_new_password.html\'>验证密码</a></li></a>");
document.writeln("                    <li><a href=\'Retrieve_password.html\'>找回密码</a></li></a>");
document.writeln("                    <li><a href=\'VIP.html\'>申请会员级别</a></li></a>");
document.writeln("                	</ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'aside-lf-content\'>");
document.writeln("					<h3  class=\'iconb4\'>仓储服务<a href=\'Warehousing_service.html\'></a></h3>");
document.writeln("                	<ul class=\'content\' style=\'display:block\'>");
document.writeln("                	<li class=\'tit\'><a href=\'Warehousing_service.html\'>我的仓库</a></li>");
document.writeln("                	<li class=\'tit\'><a href=\'../orderConLogistics.html\' target=\'_blank\'>发货到仓库</a></li>");
document.writeln("                	</ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");